use DB_INTELLECT


insert into Pais (Nombre)
values  ('Afganistán'),
        ('Albania'),
        ('Alemania'),
        ('Andorra'),
        ('Angola'),
        ('Anguila'),
        ('Antártida'),
        ('Antigua y Barbuda'),
        ('Arabia Saudí'),
        ('Argelia'),
        ('Argentina'),
        ('Armenia'),
        ('Aruba'),
        ('Australia'),
        ('Austria'),
        ('Azerbaiyán'),
        ('Bahamas'),
        ('Bangladés'),
        ('Barbados'),
        ('Baréin'),
        ('Bélgica'),
        ('Belice'),
        ('Benín'),
        ('Bermudas'),
        ('Bielorrusia'),
        ('Bolivia'),
        ('Bosnia-Herzegovina'),
        ('Botsuana'),
        ('Brasil'),
        ('Brunéi'),
        ('Bulgaria'),
        ('Burkina Faso'),
        ('Burundi'),
        ('Bután'),
        ('Cabo Verde'),
        ('Camboya'),
        ('Camerún'),
        ('Canadá'),
        ('Canarias'),
        ('Caribe neerlandés'),
        ('Catar'),
        ('Ceuta y Melilla'),
        ('Chad'),
        ('Chequia'),
        ('Chile'),
        ('China'),
        ('Chipre'),
        ('Ciudad del Vaticano'),
        ('Colombia'),
        ('Comoras'),
        ('Corea del Norte'),
        ('Corea del Sur'),
        ('Costa Rica'),
        ('Côte d’Ivoire'),
        ('Croacia'),
        ('Cuba'),
        ('Curazao'),
        ('Diego García'),
        ('Dinamarca'),
        ('Dominica'),
        ('Ecuador'),
        ('Egipto'),
        ('El Salvador'),
        ('Emiratos Árabes Unidos'),
        ('Eritrea'),
        ('Eslovaquia'),
        ('Eslovenia'),
        ('España'),
        ('Estados Unidos'),
        ('Estonia'),
        ('Etiopía'),
        ('Eurozone'),
        ('Filipinas'),
        ('Finlandia'),
        ('Fiyi'),
        ('Francia'),
        ('Gabón'),
        ('Gambia'),
        ('Georgia'),
        ('Ghana'),
        ('Gibraltar'),
        ('Granada'),
        ('Grecia'),
        ('Groenlandia'),
        ('Guadalupe'),
        ('Guam'),
        ('Guatemala'),
        ('Guayana Francesa'),
        ('Guernesey'),
        ('Guinea'),
        ('Guinea Ecuatorial'),
        ('Guinea-Bisáu'),
        ('Guyana'),
        ('Haití'),
        ('Honduras'),
        ('Hungría'),
        ('India'),
        ('Indonesia'),
        ('Irak'),
        ('Irán'),
        ('Irlanda'),
        ('Isla de la Ascensión'),
        ('Isla de Man'),
        ('Isla de Navidad'),
        ('Isla Norfolk'),
        ('Islandia'),
        ('Islas Åland'),
        ('Islas Caimán'),
        ('Islas Cocos'),
        ('Islas Cook'),
        ('Islas Feroe'),
        ('Islas Georgia del Sur y Sandwich del Sur'),
        ('Islas Malvinas'),
        ('Islas Marianas del Norte'),
        ('Islas Marshall'),
        ('Islas menores alejadas de EE. UU.'),
        ('Islas Pitcairn'),
        ('Islas Salomón'),
        ('Islas Turcas y Caicos'),
        ('Islas Vírgenes Británicas'),
        ('Islas Vírgenes de EE. UU.'),
        ('Israel'),
        ('Italia'),
        ('Jamaica'),
        ('Japón'),
        ('Jersey'),
        ('Jordania'),
        ('Kazajistán'),
        ('Kenia'),
        ('Kirguistán'),
        ('Kiribati'),
        ('Kosovo'),
        ('Kuwait'),
        ('Laos'),
        ('Lesoto'),
        ('Letonia'),
        ('Líbano'),
        ('Liberia'),
        ('Libia'),
        ('Liechtenstein'),
        ('Lituania'),
        ('Luxemburgo'),
        ('Macedonia'),
        ('Madagascar'),
        ('Malasia'),
        ('Malaui'),
        ('Maldivas'),
        ('Mali'),
        ('Malta'),
        ('Marruecos'),
        ('Martinica'),
        ('Mauricio'),
        ('Mauritania'),
        ('Mayotte'),
        ('México'),
        ('Micronesia'),
        ('Moldavia'),
        ('Mónaco'),
        ('Mongolia'),
        ('Montenegro'),
        ('Montserrat'),
        ('Mozambique'),
        ('Myanmar'),
        ('Namibia'),
        ('Nauru'),
        ('Nepal'),
        ('Nicaragua'),
        ('Níger'),
        ('Nigeria'),
        ('Niue'),
        ('Noruega'),
        ('Nueva Caledonia'),
        ('Nueva Zelanda'),
        ('Omán'),
        ('Países Bajos'),
        ('Pakistán'),
        ('Palaos'),
        ('Panamá'),
        ('Papúa Nueva Guinea'),
        ('Paraguay'),
        ('Perú'),
        ('Polinesia Francesa'),
        ('Polonia'),
        ('Portugal'),
        ('Puerto Rico'),
        ('RAE de Hong Kong'),
        ('RAE de Macao'),
        ('Reino Unido'),
        ('República Centroafricana'),
        ('República del Congo'),
        ('República Democrática del Congo'),
        ('República Dominicana'),
        ('Reunión'),
        ('Ruanda'),
        ('Rumanía'),
        ('Rusia'),
        ('Sáhara Occidental'),
        ('Samoa'),
        ('Samoa Americana'),
        ('San Bartolomé'),
        ('San Cristóbal y Nieves'),
        ('San Marino'),
        ('San Martín'),
        ('San Pedro y Miquelón'),
        ('San Vicente y las Granadinas'),
        ('Santa Elena'),
        ('Santa Lucía'),
        ('Santo Tomé y Príncipe'),
        ('Senegal'),
        ('Serbia'),
        ('Seychelles'),
        ('Sierra Leona'),
        ('Singapur'),
        ('Sint Maarten'),
        ('Siria'),
        ('Somalia'),
        ('Sri Lanka'),
        ('Suazilandia'),
        ('Sudáfrica'),
        ('Sudán'),
        ('Sudán del Sur'),
        ('Suecia'),
        ('Suiza'),
        ('Surinam'),
        ('Svalbard y Jan Mayen'),
        ('Tailandia'),
        ('Taiwán'),
        ('Tanzania'),
        ('Tayikistán'),
        ('Territorio Británico del Océano Índico'),
        ('Territorios Australes Franceses'),
        ('Territorios Palestinos'),
        ('Timor-Leste'),
        ('Togo'),
        ('Tokelau'),
        ('Tonga'),
        ('Trinidad y Tobago'),
        ('Tristán de Acuña'),
        ('Túnez'),
        ('Turkmenistán'),
        ('Turquía'),
        ('Tuvalu'),
        ('Ucrania'),
        ('Uganda'),
        ('United Nations'),
        ('Uruguay'),
        ('Uzbekistán'),
        ('Vanuatu'),
        ('Venezuela'),
        ('Vietnam'),
        ('Wallis y Futuna'),
        ('Yemen'),
        ('Yibuti'),
        ('Zambia'),
        ('Zimbabue')

insert into Usuario (Correo,				Nombre, Apellido,   FechaNac,	FechaIni,	NombrePais, Superuser, PasswordHash)
values				('danidiaza@gmail.com', 'Daniel', 'Diaz', '19940413', '20180711', 'Costa Rica', 1, 0xe4b6766a3a3d7eac1bc5e773e0e910d8efe9beda65225ad108f39abc817f6671d0406b2697c4ce43621ba9f2377217ba72c021bd96e666390428dcf46b2c55ee)

insert into Compra (Correo, Fecha, Hora, NumTokens, PrecioToken)
values				('danidiaza@gmail.com', '20180711', '12:18:00', 5, 1)

insert into Compra (Correo, Fecha, Hora, NumTokens, PrecioToken)
values				('danidiaza@gmail.com', '20180711', '12:19:00', 1, 1)

insert into Compra (Correo, Fecha, Hora, NumTokens, PrecioToken)
values				('danidiaza@gmail.com', '20180711', '12:20:00', 2, 1)

select * from Compra

declare @mytokens int
exec TokensRestantes 'danidiaza@gmail.com', @mytokens output
print (@mytokens)


insert into Cancion
values (0)
insert into Cancion
values (1)
insert into Cancion
values (2)

insert into MP3
values		(0, '0x00000000'),
			(2, '0x00c0ffee')

insert into Link
values		(1, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ')

insert into Metadato
values		(1, 'artist', 'Rick Astley'),
			(1, 'title', 'Never Gonna Give You Up'),
			(0, 'artist', 'Fabricio Alvarado'),
			(0, 'title', 'Batalla Espiritual'),
			(2, 'artist', 'Psy'),
			(2, 'title', 'Gentleman')

insert into Procesa 
values		('danidiaza@gmail.com', 1, '20180711', '0.0.1')

insert into Procesa 
values		('danidiaza@gmail.com', 2, '20180711', '0.0.1')

declare @mytokens int
exec TokensRestantes 'danidiaza@gmail.com', @mytokens output
print (@mytokens)